spring:
  jpa:
    databaseplatform: mysql
    database-platform: mysql
    databasePlatform: mysql
    database_platform: mysql

spring:
  my-example:
    url:
      - http://example.com
      - http://spring.io

spring:
  my-example:
    url: http://example.com, http://spring.io

spring:
  my-example:
    foo: bar
    hello: world

# 注意：如果Map类型的key包含非字母数字和-的字符，需要用[]括起来，比如：
spring:
  my-example:
    '[foo.baz]': bar